/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BudgetsIndexRouteImport } from './routes/budgets/index'
import { Route as BudgetsBudgetIdRouteImport } from './routes/budgets/$budgetId'
import { Route as BudgetsBalancingRouteImport } from './routes/budgets/balancing'
import { Route as BudgetsBudgetIdIndexRouteImport } from './routes/budgets/$budgetId/index'
import { Route as BudgetsBudgetIdPayeesRouteImport } from './routes/budgets/$budgetId/payees'
import { Route as BudgetsBudgetIdAccountsIndexRouteImport } from './routes/budgets/$budgetId/accounts/index'
import { Route as BudgetsBudgetIdAccountsAccountIdRouteImport } from './routes/budgets/$budgetId/accounts/$accountId'
import { Route as BudgetsBudgetIdAccountsAllRouteImport } from './routes/budgets/$budgetId/accounts/all'
import { Route as BudgetsBudgetIdCategoriesIndexRouteImport } from './routes/budgets/$budgetId/categories/index'
import { Route as BudgetsBudgetIdReportsIndexRouteImport } from './routes/budgets/$budgetId/reports/index'
import { Route as BudgetsBudgetIdReportsReportIdRouteImport } from './routes/budgets/$budgetId/reports/$reportId'
import { Route as BudgetsBudgetIdScheduledIndexRouteImport } from './routes/budgets/$budgetId/scheduled/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BudgetsIndexRoute = BudgetsIndexRouteImport.update({
  id: '/budgets/',
  path: '/budgets/',
  getParentRoute: () => rootRouteImport,
} as any)
const BudgetsBudgetIdRoute = BudgetsBudgetIdRouteImport.update({
  id: '/budgets/$budgetId',
  path: '/budgets/$budgetId',
  getParentRoute: () => rootRouteImport,
} as any)
const BudgetsBalancingRoute = BudgetsBalancingRouteImport.update({
  id: '/budgets/balancing',
  path: '/budgets/balancing',
  getParentRoute: () => rootRouteImport,
} as any)
const BudgetsBudgetIdIndexRoute = BudgetsBudgetIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BudgetsBudgetIdRoute,
} as any)
const BudgetsBudgetIdPayeesRoute = BudgetsBudgetIdPayeesRouteImport.update({
  id: '/payees',
  path: '/payees',
  getParentRoute: () => BudgetsBudgetIdRoute,
} as any)
const BudgetsBudgetIdAccountsIndexRoute =
  BudgetsBudgetIdAccountsIndexRouteImport.update({
    id: '/accounts/',
    path: '/accounts/',
    getParentRoute: () => BudgetsBudgetIdRoute,
  } as any)
const BudgetsBudgetIdAccountsAccountIdRoute =
  BudgetsBudgetIdAccountsAccountIdRouteImport.update({
    id: '/accounts/$accountId',
    path: '/accounts/$accountId',
    getParentRoute: () => BudgetsBudgetIdRoute,
  } as any)
const BudgetsBudgetIdAccountsAllRoute =
  BudgetsBudgetIdAccountsAllRouteImport.update({
    id: '/accounts/all',
    path: '/accounts/all',
    getParentRoute: () => BudgetsBudgetIdRoute,
  } as any)
const BudgetsBudgetIdCategoriesIndexRoute =
  BudgetsBudgetIdCategoriesIndexRouteImport.update({
    id: '/categories/',
    path: '/categories/',
    getParentRoute: () => BudgetsBudgetIdRoute,
  } as any)
const BudgetsBudgetIdReportsIndexRoute =
  BudgetsBudgetIdReportsIndexRouteImport.update({
    id: '/reports/',
    path: '/reports/',
    getParentRoute: () => BudgetsBudgetIdRoute,
  } as any)
const BudgetsBudgetIdReportsReportIdRoute =
  BudgetsBudgetIdReportsReportIdRouteImport.update({
    id: '/reports/$reportId',
    path: '/reports/$reportId',
    getParentRoute: () => BudgetsBudgetIdRoute,
  } as any)
const BudgetsBudgetIdScheduledIndexRoute =
  BudgetsBudgetIdScheduledIndexRouteImport.update({
    id: '/scheduled/',
    path: '/scheduled/',
    getParentRoute: () => BudgetsBudgetIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/budgets/$budgetId': typeof BudgetsBudgetIdRouteWithChildren
  '/budgets/balancing': typeof BudgetsBalancingRoute
  '/budgets/': typeof BudgetsIndexRoute
  '/budgets/$budgetId/payees': typeof BudgetsBudgetIdPayeesRoute
  '/budgets/$budgetId/': typeof BudgetsBudgetIdIndexRoute
  '/budgets/$budgetId/accounts/$accountId': typeof BudgetsBudgetIdAccountsAccountIdRoute
  '/budgets/$budgetId/accounts/all': typeof BudgetsBudgetIdAccountsAllRoute
  '/budgets/$budgetId/reports/$reportId': typeof BudgetsBudgetIdReportsReportIdRoute
  '/budgets/$budgetId/accounts/': typeof BudgetsBudgetIdAccountsIndexRoute
  '/budgets/$budgetId/categories/': typeof BudgetsBudgetIdCategoriesIndexRoute
  '/budgets/$budgetId/reports/': typeof BudgetsBudgetIdReportsIndexRoute
  '/budgets/$budgetId/scheduled/': typeof BudgetsBudgetIdScheduledIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/budgets/balancing': typeof BudgetsBalancingRoute
  '/budgets': typeof BudgetsIndexRoute
  '/budgets/$budgetId/payees': typeof BudgetsBudgetIdPayeesRoute
  '/budgets/$budgetId': typeof BudgetsBudgetIdIndexRoute
  '/budgets/$budgetId/accounts/$accountId': typeof BudgetsBudgetIdAccountsAccountIdRoute
  '/budgets/$budgetId/accounts/all': typeof BudgetsBudgetIdAccountsAllRoute
  '/budgets/$budgetId/reports/$reportId': typeof BudgetsBudgetIdReportsReportIdRoute
  '/budgets/$budgetId/accounts': typeof BudgetsBudgetIdAccountsIndexRoute
  '/budgets/$budgetId/categories': typeof BudgetsBudgetIdCategoriesIndexRoute
  '/budgets/$budgetId/reports': typeof BudgetsBudgetIdReportsIndexRoute
  '/budgets/$budgetId/scheduled': typeof BudgetsBudgetIdScheduledIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/budgets/$budgetId': typeof BudgetsBudgetIdRouteWithChildren
  '/budgets/balancing': typeof BudgetsBalancingRoute
  '/budgets/': typeof BudgetsIndexRoute
  '/budgets/$budgetId/payees': typeof BudgetsBudgetIdPayeesRoute
  '/budgets/$budgetId/': typeof BudgetsBudgetIdIndexRoute
  '/budgets/$budgetId/accounts/$accountId': typeof BudgetsBudgetIdAccountsAccountIdRoute
  '/budgets/$budgetId/accounts/all': typeof BudgetsBudgetIdAccountsAllRoute
  '/budgets/$budgetId/reports/$reportId': typeof BudgetsBudgetIdReportsReportIdRoute
  '/budgets/$budgetId/accounts/': typeof BudgetsBudgetIdAccountsIndexRoute
  '/budgets/$budgetId/categories/': typeof BudgetsBudgetIdCategoriesIndexRoute
  '/budgets/$budgetId/reports/': typeof BudgetsBudgetIdReportsIndexRoute
  '/budgets/$budgetId/scheduled/': typeof BudgetsBudgetIdScheduledIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/budgets/$budgetId'
    | '/budgets/balancing'
    | '/budgets/'
    | '/budgets/$budgetId/payees'
    | '/budgets/$budgetId/'
    | '/budgets/$budgetId/accounts/$accountId'
    | '/budgets/$budgetId/accounts/all'
    | '/budgets/$budgetId/reports/$reportId'
    | '/budgets/$budgetId/accounts/'
    | '/budgets/$budgetId/categories/'
    | '/budgets/$budgetId/reports/'
    | '/budgets/$budgetId/scheduled/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/budgets/balancing'
    | '/budgets'
    | '/budgets/$budgetId/payees'
    | '/budgets/$budgetId'
    | '/budgets/$budgetId/accounts/$accountId'
    | '/budgets/$budgetId/accounts/all'
    | '/budgets/$budgetId/reports/$reportId'
    | '/budgets/$budgetId/accounts'
    | '/budgets/$budgetId/categories'
    | '/budgets/$budgetId/reports'
    | '/budgets/$budgetId/scheduled'
  id:
    | '__root__'
    | '/'
    | '/budgets/$budgetId'
    | '/budgets/balancing'
    | '/budgets/'
    | '/budgets/$budgetId/payees'
    | '/budgets/$budgetId/'
    | '/budgets/$budgetId/accounts/$accountId'
    | '/budgets/$budgetId/accounts/all'
    | '/budgets/$budgetId/reports/$reportId'
    | '/budgets/$budgetId/accounts/'
    | '/budgets/$budgetId/categories/'
    | '/budgets/$budgetId/reports/'
    | '/budgets/$budgetId/scheduled/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BudgetsBudgetIdRoute: typeof BudgetsBudgetIdRouteWithChildren
  BudgetsBalancingRoute: typeof BudgetsBalancingRoute
  BudgetsIndexRoute: typeof BudgetsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/budgets/': {
      id: '/budgets/'
      path: '/budgets'
      fullPath: '/budgets/'
      preLoaderRoute: typeof BudgetsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/budgets/$budgetId': {
      id: '/budgets/$budgetId'
      path: '/budgets/$budgetId'
      fullPath: '/budgets/$budgetId'
      preLoaderRoute: typeof BudgetsBudgetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/budgets/balancing': {
      id: '/budgets/balancing'
      path: '/budgets/balancing'
      fullPath: '/budgets/balancing'
      preLoaderRoute: typeof BudgetsBalancingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/budgets/$budgetId/': {
      id: '/budgets/$budgetId/'
      path: '/'
      fullPath: '/budgets/$budgetId/'
      preLoaderRoute: typeof BudgetsBudgetIdIndexRouteImport
      parentRoute: typeof BudgetsBudgetIdRoute
    }
    '/budgets/$budgetId/payees': {
      id: '/budgets/$budgetId/payees'
      path: '/payees'
      fullPath: '/budgets/$budgetId/payees'
      preLoaderRoute: typeof BudgetsBudgetIdPayeesRouteImport
      parentRoute: typeof BudgetsBudgetIdRoute
    }
    '/budgets/$budgetId/accounts/': {
      id: '/budgets/$budgetId/accounts/'
      path: '/accounts'
      fullPath: '/budgets/$budgetId/accounts/'
      preLoaderRoute: typeof BudgetsBudgetIdAccountsIndexRouteImport
      parentRoute: typeof BudgetsBudgetIdRoute
    }
    '/budgets/$budgetId/accounts/$accountId': {
      id: '/budgets/$budgetId/accounts/$accountId'
      path: '/accounts/$accountId'
      fullPath: '/budgets/$budgetId/accounts/$accountId'
      preLoaderRoute: typeof BudgetsBudgetIdAccountsAccountIdRouteImport
      parentRoute: typeof BudgetsBudgetIdRoute
    }
    '/budgets/$budgetId/accounts/all': {
      id: '/budgets/$budgetId/accounts/all'
      path: '/accounts/all'
      fullPath: '/budgets/$budgetId/accounts/all'
      preLoaderRoute: typeof BudgetsBudgetIdAccountsAllRouteImport
      parentRoute: typeof BudgetsBudgetIdRoute
    }
    '/budgets/$budgetId/categories/': {
      id: '/budgets/$budgetId/categories/'
      path: '/categories'
      fullPath: '/budgets/$budgetId/categories/'
      preLoaderRoute: typeof BudgetsBudgetIdCategoriesIndexRouteImport
      parentRoute: typeof BudgetsBudgetIdRoute
    }
    '/budgets/$budgetId/reports/': {
      id: '/budgets/$budgetId/reports/'
      path: '/reports'
      fullPath: '/budgets/$budgetId/reports/'
      preLoaderRoute: typeof BudgetsBudgetIdReportsIndexRouteImport
      parentRoute: typeof BudgetsBudgetIdRoute
    }
    '/budgets/$budgetId/reports/$reportId': {
      id: '/budgets/$budgetId/reports/$reportId'
      path: '/reports/$reportId'
      fullPath: '/budgets/$budgetId/reports/$reportId'
      preLoaderRoute: typeof BudgetsBudgetIdReportsReportIdRouteImport
      parentRoute: typeof BudgetsBudgetIdRoute
    }
    '/budgets/$budgetId/scheduled/': {
      id: '/budgets/$budgetId/scheduled/'
      path: '/scheduled'
      fullPath: '/budgets/$budgetId/scheduled/'
      preLoaderRoute: typeof BudgetsBudgetIdScheduledIndexRouteImport
      parentRoute: typeof BudgetsBudgetIdRoute
    }
  }
}

interface BudgetsBudgetIdRouteChildren {
  BudgetsBudgetIdPayeesRoute: typeof BudgetsBudgetIdPayeesRoute
  BudgetsBudgetIdIndexRoute: typeof BudgetsBudgetIdIndexRoute
  BudgetsBudgetIdAccountsAccountIdRoute: typeof BudgetsBudgetIdAccountsAccountIdRoute
  BudgetsBudgetIdAccountsAllRoute: typeof BudgetsBudgetIdAccountsAllRoute
  BudgetsBudgetIdReportsReportIdRoute: typeof BudgetsBudgetIdReportsReportIdRoute
  BudgetsBudgetIdAccountsIndexRoute: typeof BudgetsBudgetIdAccountsIndexRoute
  BudgetsBudgetIdCategoriesIndexRoute: typeof BudgetsBudgetIdCategoriesIndexRoute
  BudgetsBudgetIdReportsIndexRoute: typeof BudgetsBudgetIdReportsIndexRoute
  BudgetsBudgetIdScheduledIndexRoute: typeof BudgetsBudgetIdScheduledIndexRoute
}

const BudgetsBudgetIdRouteChildren: BudgetsBudgetIdRouteChildren = {
  BudgetsBudgetIdPayeesRoute: BudgetsBudgetIdPayeesRoute,
  BudgetsBudgetIdIndexRoute: BudgetsBudgetIdIndexRoute,
  BudgetsBudgetIdAccountsAccountIdRoute: BudgetsBudgetIdAccountsAccountIdRoute,
  BudgetsBudgetIdAccountsAllRoute: BudgetsBudgetIdAccountsAllRoute,
  BudgetsBudgetIdReportsReportIdRoute: BudgetsBudgetIdReportsReportIdRoute,
  BudgetsBudgetIdAccountsIndexRoute: BudgetsBudgetIdAccountsIndexRoute,
  BudgetsBudgetIdCategoriesIndexRoute: BudgetsBudgetIdCategoriesIndexRoute,
  BudgetsBudgetIdReportsIndexRoute: BudgetsBudgetIdReportsIndexRoute,
  BudgetsBudgetIdScheduledIndexRoute: BudgetsBudgetIdScheduledIndexRoute,
}

const BudgetsBudgetIdRouteWithChildren = BudgetsBudgetIdRoute._addFileChildren(
  BudgetsBudgetIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BudgetsBudgetIdRoute: BudgetsBudgetIdRouteWithChildren,
  BudgetsBalancingRoute: BudgetsBalancingRoute,
  BudgetsIndexRoute: BudgetsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
